version: '3.7'
services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        expose:
            - "9200"
            - "9300"
        ports:
            - "9200:9200"
            - "9300:9300"
        # volumes:
            # - data_elastic:/usr/share/elasticsearch/data
            # - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

    kibana:
        image: kibana:7.6.2
        container_name: kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch

    fluentd:
        build: ./fluentd
        image:  fluentd:my
        container_name: fluentd
        expose:
            - "24224"
        ports:
            - "24224:24224"
            - "24224:24224/udp"
        volumes:
            - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
        depends_on:
            - elasticsearch
            - kibana

    postgres:
        image: postgres:12.2
        container_name: postgres
        hostname: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: test-efk
        ports:
            - "5432:5432"
        logging:
            driver: "fluentd"
            options:
                fluentd-address: "tcp://localhost:24224"
                tag: postgres
        depends_on:
            - fluentd

# volumes:
    # data_elastic:
        # driver: local
        # name: "data_elastic"

